name: FastAPI workflow

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Install Dependencies
      run: |
        apt-get update 
        apt-get install netcat-traditional -y
        pip install -U pipenv 
        pipenv install --system

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          pytest
